version: '3.8'

services:
    mongodb:
        image: mongo:latest
        container_name: my_mongo_db
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
        restart: always

volumes:
    mongodb_data:
        driver: local